// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package sqlboilr

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarchars)
}

func TestDelete(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsExists)
}

func TestFind(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsFind)
}

func TestBind(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsBind)
}

func TestOne(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsOne)
}

func TestAll(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsAll)
}

func TestCount(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsCount)
}

func TestHooks(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsInsert)
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsSliceUpdateAll)
}

func TestUpsert(t *testing.T) {
	t.Run("CatalogProductEntityVarchars", testCatalogProductEntityVarcharsUpsert)
}
