// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package sqlboilr

var TableNames = struct {
	CatalogProductEntityVarchar string
}{
	CatalogProductEntityVarchar: "catalog_product_entity_varchar",
}
