// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package sqlboilr

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/randomize"
	"github.com/vattle/sqlboiler/strmangle"
)

func testCatalogProductEntityVarchars(t *testing.T) {
	t.Parallel()

	query := CatalogProductEntityVarchars(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testCatalogProductEntityVarcharsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = catalogProductEntityVarchar.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCatalogProductEntityVarcharsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = CatalogProductEntityVarchars(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCatalogProductEntityVarcharsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := CatalogProductEntityVarcharSlice{catalogProductEntityVarchar}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testCatalogProductEntityVarcharsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := CatalogProductEntityVarcharExists(tx, catalogProductEntityVarchar.ValueID)
	if err != nil {
		t.Errorf("Unable to check if CatalogProductEntityVarchar exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CatalogProductEntityVarcharExistsG to return true, but got false.")
	}
}
func testCatalogProductEntityVarcharsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	catalogProductEntityVarcharFound, err := FindCatalogProductEntityVarchar(tx, catalogProductEntityVarchar.ValueID)
	if err != nil {
		t.Error(err)
	}

	if catalogProductEntityVarcharFound == nil {
		t.Error("want a record, got nil")
	}
}
func testCatalogProductEntityVarcharsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = CatalogProductEntityVarchars(tx).Bind(catalogProductEntityVarchar); err != nil {
		t.Error(err)
	}
}

func testCatalogProductEntityVarcharsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := CatalogProductEntityVarchars(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCatalogProductEntityVarcharsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarcharOne := &CatalogProductEntityVarchar{}
	catalogProductEntityVarcharTwo := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarcharOne, catalogProductEntityVarcharDBTypes, false, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}
	if err = randomize.Struct(seed, catalogProductEntityVarcharTwo, catalogProductEntityVarcharDBTypes, false, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarcharOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = catalogProductEntityVarcharTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := CatalogProductEntityVarchars(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCatalogProductEntityVarcharsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	catalogProductEntityVarcharOne := &CatalogProductEntityVarchar{}
	catalogProductEntityVarcharTwo := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarcharOne, catalogProductEntityVarcharDBTypes, false, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}
	if err = randomize.Struct(seed, catalogProductEntityVarcharTwo, catalogProductEntityVarcharDBTypes, false, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarcharOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = catalogProductEntityVarcharTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func catalogProductEntityVarcharBeforeInsertHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func catalogProductEntityVarcharAfterInsertHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func catalogProductEntityVarcharAfterSelectHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func catalogProductEntityVarcharBeforeUpdateHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func catalogProductEntityVarcharAfterUpdateHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func catalogProductEntityVarcharBeforeDeleteHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func catalogProductEntityVarcharAfterDeleteHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func catalogProductEntityVarcharBeforeUpsertHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func catalogProductEntityVarcharAfterUpsertHook(e boil.Executor, o *CatalogProductEntityVarchar) error {
	*o = CatalogProductEntityVarchar{}
	return nil
}

func testCatalogProductEntityVarcharsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &CatalogProductEntityVarchar{}
	o := &CatalogProductEntityVarchar{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, catalogProductEntityVarcharDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar object: %s", err)
	}

	AddCatalogProductEntityVarcharHook(boil.BeforeInsertHook, catalogProductEntityVarcharBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharBeforeInsertHooks = []CatalogProductEntityVarcharHook{}

	AddCatalogProductEntityVarcharHook(boil.AfterInsertHook, catalogProductEntityVarcharAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharAfterInsertHooks = []CatalogProductEntityVarcharHook{}

	AddCatalogProductEntityVarcharHook(boil.AfterSelectHook, catalogProductEntityVarcharAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharAfterSelectHooks = []CatalogProductEntityVarcharHook{}

	AddCatalogProductEntityVarcharHook(boil.BeforeUpdateHook, catalogProductEntityVarcharBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharBeforeUpdateHooks = []CatalogProductEntityVarcharHook{}

	AddCatalogProductEntityVarcharHook(boil.AfterUpdateHook, catalogProductEntityVarcharAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharAfterUpdateHooks = []CatalogProductEntityVarcharHook{}

	AddCatalogProductEntityVarcharHook(boil.BeforeDeleteHook, catalogProductEntityVarcharBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharBeforeDeleteHooks = []CatalogProductEntityVarcharHook{}

	AddCatalogProductEntityVarcharHook(boil.AfterDeleteHook, catalogProductEntityVarcharAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharAfterDeleteHooks = []CatalogProductEntityVarcharHook{}

	AddCatalogProductEntityVarcharHook(boil.BeforeUpsertHook, catalogProductEntityVarcharBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharBeforeUpsertHooks = []CatalogProductEntityVarcharHook{}

	AddCatalogProductEntityVarcharHook(boil.AfterUpsertHook, catalogProductEntityVarcharAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	catalogProductEntityVarcharAfterUpsertHooks = []CatalogProductEntityVarcharHook{}
}
func testCatalogProductEntityVarcharsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCatalogProductEntityVarcharsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx, catalogProductEntityVarcharColumnsWithoutDefault...); err != nil {
		t.Error(err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCatalogProductEntityVarcharsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = catalogProductEntityVarchar.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testCatalogProductEntityVarcharsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := CatalogProductEntityVarcharSlice{catalogProductEntityVarchar}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testCatalogProductEntityVarcharsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := CatalogProductEntityVarchars(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	catalogProductEntityVarcharDBTypes = map[string]string{`AttributeID`: `smallint`, `EntityID`: `int`, `EntityTypeID`: `int`, `StoreID`: `smallint`, `Value`: `varchar`, `ValueID`: `int`}
	_                                  = bytes.MinRead
)

func testCatalogProductEntityVarcharsUpdate(t *testing.T) {
	t.Parallel()

	if len(catalogProductEntityVarcharColumns) == len(catalogProductEntityVarcharPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	if err = catalogProductEntityVarchar.Update(tx); err != nil {
		t.Error(err)
	}
}

func testCatalogProductEntityVarcharsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(catalogProductEntityVarcharColumns) == len(catalogProductEntityVarcharPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	catalogProductEntityVarchar := &CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true, catalogProductEntityVarcharPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(catalogProductEntityVarcharColumns, catalogProductEntityVarcharPrimaryKeyColumns) {
		fields = catalogProductEntityVarcharColumns
	} else {
		fields = strmangle.SetComplement(
			catalogProductEntityVarcharColumns,
			catalogProductEntityVarcharPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(catalogProductEntityVarchar))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := CatalogProductEntityVarcharSlice{catalogProductEntityVarchar}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testCatalogProductEntityVarcharsUpsert(t *testing.T) {
	t.Parallel()

	if len(catalogProductEntityVarcharColumns) == len(catalogProductEntityVarcharPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	catalogProductEntityVarchar := CatalogProductEntityVarchar{}
	if err = randomize.Struct(seed, &catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = catalogProductEntityVarchar.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert CatalogProductEntityVarchar: %s", err)
	}

	count, err := CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &catalogProductEntityVarchar, catalogProductEntityVarcharDBTypes, false, catalogProductEntityVarcharPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CatalogProductEntityVarchar struct: %s", err)
	}

	if err = catalogProductEntityVarchar.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert CatalogProductEntityVarchar: %s", err)
	}

	count, err = CatalogProductEntityVarchars(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
